### ISSUE TITLE
Make slynk port configurable

### ISSUE THREAD

**Issue by fisxoj** [fisxoj/lisp-images#1]
In cases where there are multiple lisp apps running in containers, it would be useful to be able to use different ports, something like
```
services:
  app:
    ...
    environment:
      SLYNK_PORT: 4008

  worker:
    ...
    environment:
      SLYNK_PORT: 4009
```
